services:
  postgres:
    container_name: re_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: chathura
      POSTGRES_PASSWORD: chathura
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  #    to interact with postgress
#  pgadmin:
#    container_name: re_pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - 5050:80
#    networks:
#      - microservices-net
#    restart: unless-stopped
#
#  #    mongodb
#  mongodb:
#    container_name: re_mongo_db
#    image: mongo:7.0.9
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: chathura
#      MONGO_INITDB_ROOT_PASSWORD: chathura
#
#  mongo-express:
#    container_name: re_mongo_express
#    image: mongo-express
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: chathura
#      ME_CONFIG_MONGODB_ADMINPASSWORD: chathura
#      ME_CONFIG_MONGODB_SERVER: mongodb
#    ports:
#      - 8081:8081
#    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres: